# MegaLinter workflow customized for FitFileViewer
name: MegaLinter

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: megalinter-${{ github.ref }}
  cancel-in-progress: false

jobs:
  megalinter:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: MegaLinter
        id: megalinter
        uses: oxsecurity/megalinter@8fbdead70d1409964ab3d5afa885e18ee85388bb # v9.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_LINTERS: SPELL_CSPELL
          EXCLUDED_DIRECTORIES: libs, tests, screenshots, node_modules, icons
          SHOW_ELAPSED_TIME: true
          GITHUB_STATUS_REPORTER: true
          FILEIO_REPORTER: true
          GITHUB_COMMENT_REPORTER: true
          JSON_REPORTER: true
          JSON_REPORTER_OUTPUT_DETAIL: true
          MARKDOWN_SUMMARY_REPORTER: true
          SARIF_REPORTER: true
          TAP_REPORTER: true
          TAP_REPORTER_OUTPUT_DETAIL: true
          DISABLE_ERRORS: true
          JAVASCRIPT_DEFAULT_STYLE: prettier
          PRINT_ALL_FILES: true

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: success() || failure()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
        continue-on-error: true
